# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-11 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
